title: Cielo LIO Remote Java Client
description: Remote integration with Cielo LIO Order Management.
google_analytics: 
show_downloads: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
